name: C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: script
      run: sudo apt update && sudo apt install -u libsdl2-dev && cd C++ && g++ main.cpp -lSDL2 -o main
